doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            enum: Doctrine\DBAL\Types\StringType
            sku: App\Infrastructure\Persistance\Doctrine\Types\SkuType
            currency: App\Infrastructure\Persistance\Doctrine\Types\CurrencyType
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Price:
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistance/Doctrine/Mapping/Price'
                prefix: 'App\Domain\Model\Price'
                is_bundle: false

            Product:
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistance/Doctrine/Mapping/Product'
                prefix: 'App\Domain\Model\Product'
                is_bundle: false

            Promotion:
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistance/Doctrine/Mapping/Promotion'
                prefix: 'App\Domain\Model\Promotion'
                is_bundle: false
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
