services:
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - mytheresa-network

    php:
        build:
            context: ./docker/php/local
            dockerfile: Dockerfile
            args: [ "XDEBUG_CLIENT_HOST=127.0.0.1" ]
        container_name: php
        restart: unless-stopped
        env_file:
            - .env
        environment:
            DB_HOST: mysql
            PHP_IDE_CONFIG: serverName=localhost
        ports:
            - "9000:9000"
        volumes:
            - "./:/var/www"
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - mytheresa-network

    mysql:
        build:
            context: ./docker/mysql
        container_name: mysql
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "3306:3306"
        tty: true
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "app", "-pp4ssw0rd" ]
            interval: 2s
            timeout: 20s
            retries: 10
        networks:
            - mytheresa-network

networks:
    mytheresa-network:
        name: mytheresa-network
        driver: bridge
