name: mytheresa

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build app
        run: |
          cp .env.dev .env
          make up

      - name: Wait for server
        run:        |
          sleep 10
          for i in {1..10}; do
          if curl -s http://localhost:8080/healthz; then
            echo "Service is up!"
            break
          fi
          echo "Waiting for service..."
          sleep 2
          done

      - name: Run acceptance tests
        run:  make tests
